import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { JsonLedgerStore } from "../../src/adapters/node/jsonLedgerStore";
import { renderUninstallScript, type Subscription } from "../../src/core/domain/subscriptions";

// Adapter test against a real temp dir: the frozen on-disk format
// (pretty-printed subscriptions.json keyed by lowercased repo) and the derived
// uninstall-all.bat, regenerated byte-identically on every save.

let dir: string;
let store: JsonLedgerStore;

beforeEach(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), "dcs-ledger-"));
  store = new JsonLedgerStore(() => dir);
});

afterEach(() => {
  fs.rmSync(dir, { recursive: true, force: true });
});

const sub: Subscription = {
  repo: "Owner/Repo",
  name: "My Mod",
  tag: "v1.0.0",
  dir: path.join("D:", "data", "Owner__Repo"),
  enabled: true,
  links: [{ id: "Owner/Repo:0", dest: "C:\\SG\\DCS\\Scripts\\X" }],
  entrypoints: [],
  missionScripts: [],
};

describe("load", () => {
  it("returns {} when the file is missing", async () => {
    expect(await store.load()).toEqual({});
  });

  it("returns {} when the file is unparsable (tolerant read)", async () => {
    fs.writeFileSync(store.subsFilePath(), "{not json");
    expect(await store.load()).toEqual({});
  });

  it("round-trips a saved ledger", async () => {
    await store.save({ "owner/repo": sub });
    expect(await store.load()).toEqual({ "owner/repo": sub });
  });
});

describe("save", () => {
  it("writes pretty-printed 2-space JSON (frozen format), creating the data dir", async () => {
    fs.rmSync(dir, { recursive: true, force: true }); // save must mkdir -p
    await store.save({ "owner/repo": sub });
    const raw = fs.readFileSync(store.subsFilePath(), "utf8");
    expect(raw).toBe(JSON.stringify({ "owner/repo": sub }, null, 2));
  });

  it("regenerates uninstall-all.bat byte-identically to the pure renderer", async () => {
    await store.save({ "owner/repo": sub });
    const bat = fs.readFileSync(store.uninstallBatPath(), "utf8");
    expect(bat).toBe(renderUninstallScript({ "owner/repo": sub }, dir, store.subsFilePath()));
    expect(bat.endsWith("\r\n")).toBe(true);
  });

  it("keeps the bat current across saves", async () => {
    await store.save({ "owner/repo": sub });
    await store.save({});
    const bat = fs.readFileSync(store.uninstallBatPath(), "utf8");
    expect(bat).toBe(renderUninstallScript({}, dir, store.subsFilePath()));
    expect(bat).not.toContain("Owner__Repo");
  });

  it("survives a bat write failure (best-effort) without failing the save", async () => {
    // Occupy the bat path with a directory so writeFileSync fails.
    fs.mkdirSync(store.uninstallBatPath(), { recursive: true });
    await expect(store.save({ "owner/repo": sub })).resolves.toBeUndefined();
    expect(JSON.parse(fs.readFileSync(store.subsFilePath(), "utf8"))).toEqual({ "owner/repo": sub });
  });
});

describe("ensureUninstallBat", () => {
  it("writes the empty-ledger script when nothing is installed and returns its path", () => {
    const p = store.ensureUninstallBat();
    expect(p).toBe(store.uninstallBatPath());
    expect(fs.readFileSync(p, "utf8")).toBe(renderUninstallScript({}, dir, store.subsFilePath()));
  });

  it("renders from the current ledger", async () => {
    await store.save({ "owner/repo": sub });
    fs.rmSync(store.uninstallBatPath());
    const p = store.ensureUninstallBat();
    expect(fs.readFileSync(p, "utf8")).toContain('rmdir /s /q "D:\\data\\Owner__Repo"');
  });
});
