import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { win32 as winPath } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { JsonLedgerStore } from "../../../src/adapters/node/jsonLedgerStore";
import { renderUninstallScript, type Subscription } from "../../../src/core/domain/subscriptions";

// Adapter test against a real temp dir: the frozen on-disk format
// (pretty-printed subscriptions.json keyed by lowercased repo) and the derived
// uninstall-all.bat, regenerated byte-identically on every save.

let dir: string;
let store: JsonLedgerStore;

beforeEach(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), "dcs-ledger-"));
  store = new JsonLedgerStore(() => dir);
});

afterEach(() => {
  fs.rmSync(dir, { recursive: true, force: true });
});

const sub: Subscription = {
  repo: "Owner/Repo",
  name: "My Mod",
  tag: "v1.0.0",
  // Ledger `dir` values are produced by SubscriptionService, which resolves
  // with Windows semantics regardless of host — mirror that here so the
  // rendered .bat is asserted byte-for-byte the same on any dev machine.
  dir: winPath.join("D:", "data", "Owner__Repo"),
  enabled: true,
  links: [{ id: "Owner/Repo:0", dest: "C:\\SG\\DCS\\Scripts\\X" }],
  bundles: [{ path: "Scripts/X" }],
  symlinks: [{ source: "Scripts/X", dest: "{SavedGames}/Scripts/X" }],
  entrypoints: [],
  missionScripts: [],
};

describe("load", () => {
  it("returns {} when the file is missing, which is the normal first run", async () => {
    expect(await store.load()).toEqual({});
    expect(store.takeCorruptNotice()).toBeUndefined();
    expect(fs.existsSync(store.corruptFilePath())).toBe(false);
  });

  it("round-trips a saved ledger", async () => {
    await store.save({ "owner/repo": sub });
    expect(await store.load()).toEqual({ "owner/repo": sub });
  });
});

describe("an unreadable ledger", () => {
  // Reading a corrupt ledger as empty is how every mod silently disappears from
  // My Mods while its links stay in the DCS folders. The file is the only
  // record of those links, so it is preserved and the user is told where.
  it("reads as empty but preserves the file and raises a notice", async () => {
    fs.writeFileSync(store.subsFilePath(), "{not json");

    expect(await store.load()).toEqual({});

    expect(fs.readFileSync(store.corruptFilePath(), "utf8")).toBe("{not json");
    expect(fs.existsSync(store.subsFilePath())).toBe(false);
    expect(store.takeCorruptNotice()).toBe(store.corruptFilePath());
  });

  it("treats valid JSON that is not a ledger object as unreadable", async () => {
    // `[]` and `null` parse cleanly and would otherwise be handed on as a
    // ledger, dropping every subscription just as quietly as a parse failure.
    for (const raw of ["[]", "null", "42"]) {
      fs.rmSync(store.corruptFilePath(), { force: true });
      fs.writeFileSync(store.subsFilePath(), raw);
      expect(await store.load()).toEqual({});
      expect(fs.readFileSync(store.corruptFilePath(), "utf8")).toBe(raw);
      expect(store.takeCorruptNotice()).toBe(store.corruptFilePath());
    }
  });

  it("treats a ledger that cannot be read at all as unreadable, not as absent", async () => {
    // A directory where the file should be reads as EISDIR, not ENOENT.
    fs.mkdirSync(store.subsFilePath(), { recursive: true });

    expect(await store.load()).toEqual({});

    expect(store.takeCorruptNotice()).toBe(store.corruptFilePath());
    expect(fs.statSync(store.corruptFilePath()).isDirectory()).toBe(true);
  });

  it("points at the ledger itself when it could not be preserved", async () => {
    // Something already occupies the .corrupt path — the file stays put, so the
    // notice has to name where it actually is.
    fs.writeFileSync(store.subsFilePath(), "{not json");
    fs.mkdirSync(store.corruptFilePath(), { recursive: true });
    fs.writeFileSync(path.join(store.corruptFilePath(), "keep.txt"), "x");

    expect(await store.load()).toEqual({});

    expect(store.takeCorruptNotice()).toBe(store.subsFilePath());
    expect(fs.readFileSync(store.subsFilePath(), "utf8")).toBe("{not json");
  });

  it("hands the notice out once, so the warning is not repeated on every refresh", async () => {
    fs.writeFileSync(store.subsFilePath(), "{not json");
    await store.load();

    expect(store.takeCorruptNotice()).toBe(store.corruptFilePath());
    expect(store.takeCorruptNotice()).toBeUndefined();
    // The quarantined file is gone from its old path, so the next read is a
    // clean "nothing installed yet" rather than a second warning.
    expect(await store.load()).toEqual({});
    expect(store.takeCorruptNotice()).toBeUndefined();
  });
});

describe("save", () => {
  it("writes pretty-printed 2-space JSON (frozen format), creating the data dir", async () => {
    fs.rmSync(dir, { recursive: true, force: true }); // save must mkdir -p
    await store.save({ "owner/repo": sub });
    const raw = fs.readFileSync(store.subsFilePath(), "utf8");
    expect(raw).toBe(JSON.stringify({ "owner/repo": sub }, null, 2));
  });

  it("regenerates uninstall-all.bat byte-identically to the pure renderer", async () => {
    await store.save({ "owner/repo": sub });
    const bat = fs.readFileSync(store.uninstallBatPath(), "utf8");
    expect(bat).toBe(renderUninstallScript({ "owner/repo": sub }, dir, store.subsFilePath()));
    expect(bat.endsWith("\r\n")).toBe(true);
  });

  it("keeps the bat current across saves", async () => {
    await store.save({ "owner/repo": sub });
    await store.save({});
    const bat = fs.readFileSync(store.uninstallBatPath(), "utf8");
    expect(bat).toBe(renderUninstallScript({}, dir, store.subsFilePath()));
    expect(bat).not.toContain("Owner__Repo");
  });

  it("survives a bat write failure (best-effort) without failing the save", async () => {
    // Occupy the bat path with a directory so writeFileSync fails.
    fs.mkdirSync(store.uninstallBatPath(), { recursive: true });
    await expect(store.save({ "owner/repo": sub })).resolves.toBeUndefined();
    expect(JSON.parse(fs.readFileSync(store.subsFilePath(), "utf8"))).toEqual({
      "owner/repo": sub,
    });
  });
});

describe("ensureUninstallBat", () => {
  it("writes the empty-ledger script when nothing is installed and returns its path", () => {
    const p = store.ensureUninstallBat();
    expect(p).toBe(store.uninstallBatPath());
    expect(fs.readFileSync(p, "utf8")).toBe(renderUninstallScript({}, dir, store.subsFilePath()));
  });

  it("renders from the current ledger", async () => {
    await store.save({ "owner/repo": sub });
    fs.rmSync(store.uninstallBatPath());
    const p = store.ensureUninstallBat();
    expect(fs.readFileSync(p, "utf8")).toContain('rmdir /s /q "D:\\data\\Owner__Repo"');
  });

  it("leaves the script alone when the ledger could not be read", async () => {
    // Regenerating it from an empty read would rewrite the one thing that can
    // still remove the links a corrupt ledger no longer accounts for.
    await store.save({ "owner/repo": sub });
    const before = fs.readFileSync(store.uninstallBatPath(), "utf8");
    fs.writeFileSync(store.subsFilePath(), "{not json");

    const p = store.ensureUninstallBat();

    expect(p).toBe(store.uninstallBatPath());
    expect(fs.readFileSync(p, "utf8")).toBe(before);
    expect(before).toContain("C:\\SG\\DCS\\Scripts\\X");
    expect(store.takeCorruptNotice()).toBe(store.corruptFilePath());
  });
});
