//! Live type sync (issue #50, model `studio::types::TypeSync`): pull the
//! authoritative `.d.lua` from a running DCS over the editor↔sim link and write
//! it under the project so the editor's hover and diagnostics match the EXACT
//! loaded build with zero manual upkeep.
//!
//! The sim-side emit faces are `dcs::bridge::Types` (`emit_dlua` for the
//! `dcs_studio` module, `dump_globals` for the introspected DCS API, both
//! registered as RPC methods in slice 1); this is the studio-side orchestration
//! and its guards. `root` is the project the operation targets — the open
//! workspace for the desktop `sync_types` command, the agent-supplied root for
//! the MCP `sync_types` tool — so the IDE and an agent run identical logic.
//!
//! The recorded decisions (the guards): the link must be live or the sync fails
//! closed; the sync writes ONE fixed file ([`GENERATED_FILE`]) under
//! `types/generated/` — a constant relative path, never derived from sim data,
//! disjoint from the top-level `types/*.d.lua` a project hand-writes, so a sync
//! structurally cannot clobber a hand-written stub. The file carries a version
//! stamp so drift is judged against the RUNNING build, never bytes on disk.
//!
//! Pure logic (stamp render/parse, the write target, the drift verdict) is unit
//! tested here; the live-link orchestration is exercised by review and the
//! Windows-only e2e (the bridge links DCS's `lua.dll`).

use std::path::Path;

use serde_json::{json, Value};

use crate::link::LinkShared;

/// The single `.d.lua` a sync writes, relative to the project root. A fixed,
/// internal path — never derived from sim data — under `types/generated/`, a
/// directory disjoint from the top-level `types/*.d.lua` a project hand-writes
/// (the golden `dcs_studio` stub a new project scaffolds). Because the target is
/// this constant, a sync can only ever land here and never overwrites a
/// hand-written stub.
pub const GENERATED_FILE: &str = "types/generated/dcs.d.lua";

/// First line of every generated file — marks it machine-written so a reader
/// (or a curious developer) knows not to hand-edit it.
const STAMP_HEADER: &str =
    "-- AUTOGENERATED by DCS Studio — do not edit. Run \"Sync types from DCS\" to refresh.";
/// Header comment carrying the running bridge DLL version, read back to judge
/// drift. The render and parse sides share this prefix so they cannot drift.
const STAMP_BRIDGE_PREFIX: &str = "-- @dcs-studio-bridge-version ";
/// Header comment carrying the running DCS `_APP_VERSION`.
const STAMP_DCS_PREFIX: &str = "-- @dcs-version ";

/// Eval that reads the running build's identity in one round trip: the DLL's
/// `dcs_studio.version` and DCS `_APP_VERSION`. A `nil` for either (module not
/// loaded, version global absent) rides back as JSON `null`, so the stamp is
/// refused rather than half-known.
const RUNNING_STAMP_EVAL: &str =
    "return { bridge = require('dcs_studio').version, dcs = _APP_VERSION }";

/// Version stamp written into every generated file's header and read back to
/// judge drift. `bridge_version` is the running `dcs_studio.version` (the DLL
/// constant); `dcs_version` is DCS `_APP_VERSION`. Drift is a mismatch of EITHER
/// against the running build — never an on-disk byte compare.
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize)]
pub struct TypeStamp {
    pub bridge_version: String,
    pub dcs_version: String,
}

/// Outcome of a successful sync: the generated file written, its size in bytes,
/// and the stamp it carries.
#[derive(Debug, PartialEq, Eq, serde::Serialize)]
pub struct SyncResult {
    pub path: String,
    pub bytes: u64,
    pub stamp: TypeStamp,
}

/// Drift verdict for the status bar. `in_sync` is false when the project's
/// stamped types no longer match the running build, when nothing has been synced
/// yet, or when the link is down so the running build is unknown. Both stamps are
/// surfaced (synced vs running) so the UI can name which version moved.
#[derive(Debug, PartialEq, Eq, serde::Serialize)]
pub struct DriftStatus {
    pub in_sync: bool,
    pub synced: Option<TypeStamp>,
    pub running: Option<TypeStamp>,
}

/// "Sync types from DCS" — the single developer action, over the project at
/// `root` (model `TypeSync.Sync`). Fails closed when the link is not live
/// (nothing is written; the error tells the developer to start DCS). Otherwise:
/// read the running stamp, pull the module + introspected API types, write them
/// to [`GENERATED_FILE`] under `root`, then run `reindex` — the signal the
/// language layer re-mounts on (the app emits an event; a headless caller passes
/// a no-op). The error string is surfaced to the developer/agent verbatim.
///
/// # Errors
/// The link is down (fail-closed), a version probe failed, or the guarded write
/// hit IO.
pub async fn sync(
    link: &LinkShared,
    root: &Path,
    reindex: impl FnOnce(),
) -> Result<SyncResult, String> {
    if !link.is_connected() {
        return Err("Start DCS first — live type sync needs a running sim link".to_string());
    }
    let stamp = running_stamp(link).await?;
    let defs = pull_type_defs(link).await?;
    let result = write_generated(root, &stamp, &defs)?;
    reindex();
    Ok(result)
}

/// Drift verdict for the project at `root` (model `TypeSync.Drift`): compare the
/// stamp written into the generated file against the RUNNING build pulled over
/// the link. Out of sync when no sync has run, when the link is down (running
/// build unknown), or when either version differs — never a byte compare of
/// files on disk.
pub async fn drift(link: &LinkShared, root: &Path) -> DriftStatus {
    let synced = read_synced_stamp(root);
    if synced.is_none() {
        return drift_verdict(None, false, None);
    }
    if !link.is_connected() {
        return drift_verdict(synced, false, None);
    }
    // A failed probe leaves the running build unknown — treated as drift, never
    // a false "in sync".
    let running = running_stamp(link).await.ok();
    drift_verdict(synced, true, running)
}

/// Read the running build's identity over the link (model `TypeSync.RunningStamp`)
/// in one eval. Errs (fail-closed) if either version is missing, so a half-known
/// build never produces a misleading stamp.
async fn running_stamp(link: &LinkShared) -> Result<TypeStamp, String> {
    let value = link
        .call("eval", Some(json!({ "code": RUNNING_STAMP_EVAL })))
        .await?;
    let bridge = string_field(&value, "bridge");
    let dcs = string_field(&value, "dcs");
    match (bridge, dcs) {
        (Some(bridge_version), Some(dcs_version)) => Ok(TypeStamp {
            bridge_version,
            dcs_version,
        }),
        _ => Err(
            "Could not read the running DCS build version — is the dcs_studio bridge loaded?"
                .to_string(),
        ),
    }
}

/// A non-empty string member of `value`, or `None`.
fn string_field(value: &Value, key: &str) -> Option<String> {
    value
        .get(key)
        .and_then(Value::as_str)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

/// Pull the sim's emitted types over the link (model `TypeSync.PullTypeDefs`):
/// the `dcs_studio` module (`emit_dlua`) then the introspected DCS API
/// (`dump_globals`), concatenated into one definition text.
async fn pull_type_defs(link: &LinkShared) -> Result<String, String> {
    let module = call_dlua(link, "emit_dlua").await?;
    let globals = call_dlua(link, "dump_globals").await?;
    Ok(format!("{module}\n{globals}"))
}

/// One `.d.lua`-emitting RPC: the result is `{ dlua: "…" }` (model
/// `dcs::bridge::TypeDefs`); a response missing it is an error.
async fn call_dlua(link: &LinkShared, method: &str) -> Result<String, String> {
    let value = link.call(method, None).await?;
    value
        .get("dlua")
        .and_then(Value::as_str)
        .map(str::to_string)
        .ok_or_else(|| format!("{method} did not return a .d.lua payload"))
}

/// Prepend `stamp` as a header comment to `defs` and write the result to
/// [`GENERATED_FILE`] under `root` (model `TypeSync.WriteGenerated`). The
/// relative target is that constant — no sim-derived segment — so the write
/// lands under `root`/`types/generated/` by construction and a hand-written
/// `types/*.d.lua` is structurally unreachable.
fn write_generated(root: &Path, stamp: &TypeStamp, defs: &str) -> Result<SyncResult, String> {
    let path = root.join(GENERATED_FILE);
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("create {}: {e}", dir.display()))?;
    }
    let content = render_with_stamp(stamp, defs);
    std::fs::write(&path, &content).map_err(|e| format!("write {}: {e}", path.display()))?;
    Ok(SyncResult {
        path: path.to_string_lossy().into_owned(),
        bytes: content.len() as u64,
        stamp: stamp.clone(),
    })
}

/// The full generated-file text: the do-not-edit header, the two version stamp
/// lines, then the definitions.
fn render_with_stamp(stamp: &TypeStamp, defs: &str) -> String {
    format!(
        "{STAMP_HEADER}\n{STAMP_BRIDGE_PREFIX}{}\n{STAMP_DCS_PREFIX}{}\n{defs}",
        stamp.bridge_version, stamp.dcs_version
    )
}

/// Read the stamp from the generated file's header under `root`, if a sync has
/// ever run there (model `TypeSync.ReadSyncedStamp`). `None` when the file is
/// absent or carries no stamp header.
fn read_synced_stamp(root: &Path) -> Option<TypeStamp> {
    let content = std::fs::read_to_string(root.join(GENERATED_FILE)).ok()?;
    parse_stamp(&content)
}

/// Parse both version lines out of a generated file's header. Both must be
/// present and non-empty, else the file is treated as unstamped.
fn parse_stamp(content: &str) -> Option<TypeStamp> {
    let mut bridge_version = None;
    let mut dcs_version = None;
    for line in content.lines() {
        if let Some(value) = line.strip_prefix(STAMP_BRIDGE_PREFIX) {
            bridge_version = non_empty(value.trim());
        } else if let Some(value) = line.strip_prefix(STAMP_DCS_PREFIX) {
            dcs_version = non_empty(value.trim());
        }
    }
    Some(TypeStamp {
        bridge_version: bridge_version?,
        dcs_version: dcs_version?,
    })
}

/// `Some(owned)` for a non-empty string, else `None`.
fn non_empty(s: &str) -> Option<String> {
    (!s.is_empty()).then(|| s.to_string())
}

/// Whether two stamps describe the same running build (model
/// `TypeSync.StampsMatch`).
fn stamps_match(a: &TypeStamp, b: &TypeStamp) -> bool {
    a == b
}

/// The drift decision (model `TypeSync.Drift` body), factored pure so the table
/// is testable without a live link: no sync → out of sync; link down → out of
/// sync (running unknown); running known → in sync iff the stamps match.
fn drift_verdict(
    synced: Option<TypeStamp>,
    live: bool,
    running: Option<TypeStamp>,
) -> DriftStatus {
    let Some(synced) = synced else {
        return DriftStatus {
            in_sync: false,
            synced: None,
            running: None,
        };
    };
    if !live {
        return DriftStatus {
            in_sync: false,
            synced: Some(synced),
            running: None,
        };
    }
    let Some(running) = running else {
        return DriftStatus {
            in_sync: false,
            synced: Some(synced),
            running: None,
        };
    };
    DriftStatus {
        in_sync: stamps_match(&synced, &running),
        synced: Some(synced),
        running: Some(running),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn stamp(bridge: &str, dcs: &str) -> TypeStamp {
        TypeStamp {
            bridge_version: bridge.to_string(),
            dcs_version: dcs.to_string(),
        }
    }

    /// A throwaway project root, removed on drop.
    struct TempRoot(PathBuf);

    impl TempRoot {
        fn new(tag: &str) -> Self {
            let nanos = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map_or(0, |d| d.as_nanos());
            let root =
                std::env::temp_dir().join(format!("dcs-types-{tag}-{}-{nanos}", std::process::id()));
            let _ = std::fs::remove_dir_all(&root);
            std::fs::create_dir_all(&root).expect("create temp root");
            TempRoot(root)
        }
    }

    impl Drop for TempRoot {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn stamp_round_trips_through_the_generated_header() {
        let s = stamp("0.4.2", "2.9.6.1234");
        let rendered = render_with_stamp(&s, "DCS = {}\nfunction DCS.getModelTime() end\n");
        // The defs survive verbatim alongside the header…
        assert!(rendered.contains("DCS = {}"), "defs dropped: {rendered}");
        assert!(rendered.starts_with(STAMP_HEADER), "no do-not-edit header");
        // …and the stamp reads back exactly.
        assert_eq!(parse_stamp(&rendered), Some(s));
    }

    #[test]
    fn parse_stamp_needs_both_versions() {
        // Only one marker present → unstamped.
        let half = format!("{STAMP_BRIDGE_PREFIX}0.4.2\nDCS = {{}}\n");
        assert_eq!(parse_stamp(&half), None);
        // An empty version value is not a version.
        let blank = format!("{STAMP_BRIDGE_PREFIX}\n{STAMP_DCS_PREFIX}2.9\n");
        assert_eq!(parse_stamp(&blank), None);
    }

    #[test]
    fn write_generated_lands_under_types_generated_and_spares_hand_written_stubs() {
        let root = TempRoot::new("write");
        // A hand-written top-level stub the sync must never touch.
        std::fs::create_dir_all(root.0.join("types")).expect("types dir");
        let hand = root.0.join("types").join("dcs_studio.d.lua");
        std::fs::write(&hand, "-- mine\n").expect("write stub");

        let s = stamp("0.4.2", "2.9.6.1234");
        let result = write_generated(&root.0, &s, "DCS = {}\n").expect("write generated");

        let generated = root.0.join(GENERATED_FILE);
        assert!(generated.is_file(), "generated file not written");
        assert_eq!(result.path, generated.to_string_lossy());
        assert_eq!(result.stamp, s);
        let on_disk = std::fs::read_to_string(&generated).expect("read generated");
        assert_eq!(result.bytes as usize, on_disk.len(), "byte count mismatch");

        // The hand-written stub is byte-for-byte untouched.
        assert_eq!(std::fs::read_to_string(&hand).expect("read stub"), "-- mine\n");
        // And the round-trip stamp matches.
        assert_eq!(read_synced_stamp(&root.0), Some(s));
    }

    #[test]
    fn read_synced_stamp_is_none_before_any_sync() {
        let root = TempRoot::new("nostamp");
        assert_eq!(read_synced_stamp(&root.0), None);
    }

    #[test]
    fn drift_verdict_covers_every_arm() {
        let synced = stamp("0.4.2", "2.9.6.1234");
        let same = stamp("0.4.2", "2.9.6.1234");
        let newer_dll = stamp("0.4.3", "2.9.6.1234");

        // Never synced → out of sync, nothing to show.
        assert_eq!(
            drift_verdict(None, true, Some(same.clone())),
            DriftStatus { in_sync: false, synced: None, running: None }
        );
        // Synced but link down → out of sync, running unknown, last sync shown.
        assert_eq!(
            drift_verdict(Some(synced.clone()), false, None),
            DriftStatus { in_sync: false, synced: Some(synced.clone()), running: None }
        );
        // Synced, live, but the running probe failed → out of sync, running unknown.
        assert_eq!(
            drift_verdict(Some(synced.clone()), true, None),
            DriftStatus { in_sync: false, synced: Some(synced.clone()), running: None }
        );
        // Synced, live, versions match → in sync.
        assert_eq!(
            drift_verdict(Some(synced.clone()), true, Some(same.clone())),
            DriftStatus { in_sync: true, synced: Some(synced.clone()), running: Some(same) }
        );
        // Synced, live, a different build loaded → out of sync, both shown.
        assert_eq!(
            drift_verdict(Some(synced.clone()), true, Some(newer_dll.clone())),
            DriftStatus { in_sync: false, synced: Some(synced), running: Some(newer_dll) }
        );
    }
}
