// Pure generation of the two managed aggregator files DCS Studio owns in
// Saved Games/DCS/Scripts:
//   DcsStudioMissionScriptsBeforeSanitize.lua  (dofiled BEFORE the lockdown)
//   DcsStudioMissionScriptsAfterSanitize.lua   (dofiled AFTER the lockdown)
// Each file is REGENERATED FROM SCRATCH from the full set of enabled mods'
// mission scripts on every enable/disable/uninstall, so it always reflects the
// current enabled state and never references a disabled or removed mod. Each
// declares a `dofileifexist` guard (logs via env.info/env.warning and tolerates
// a missing target) then one guarded `dofile` per script, tagged with the owning
// `-- <repo>@<tag>` comment. Paths are emitted forward-slashed inside a Lua
// long-string ([[ ]]) so Windows backslashes never need escaping.
//
// This module is PURE (no I/O, no path resolution against roots): the app layer
// resolves each script's absolute unpacked path and hands entries here.

import { AFTER_SANITIZE_FILE, BEFORE_SANITIZE_FILE } from "./missionScriptTrigger";

export { AFTER_SANITIZE_FILE, BEFORE_SANITIZE_FILE };

/** One resolved mission-script entry to aggregate. */
export interface AggregatorEntry {
  /** The owning mod tag comment, e.g. `owner/repo@v1.2.0`. */
  tag: string;
  /** The absolute on-disk path of the script (any separator style). */
  absPath: string;
}

/** Convert any path to forward slashes for a Lua [[ ]] long string. */
export function toPosix(p: string): string {
  return p.replace(/\\/g, "/");
}

// The guard helper prepended to every generated file. dofileifexist logs and
// tolerates a missing target so a stale reference (or a not-yet-unpacked mod)
// can never abort mission start.
const GUARD = `-- This file is generated by DCS Studio. Do not edit — it is
-- regenerated from scratch whenever mods are enabled or disabled.

local function dofileifexist(path)
    local f = io.open(path, "r")
    if f then
        env.info("[dcs-studio] dofile: " .. path)
        f:close()
        dofile(path)
    else
        env.warning("[dcs-studio] mission script not found, skipping: " .. path)
    end
end`;

/**
 * Render one aggregator file's contents from its entries. With no entries the
 * file is still regenerated as guard-only (never deleted): the trigger line in
 * MissionScripting.lua keeps dofiling a valid, empty managed file. Uses LF and a
 * trailing newline.
 */
export function generateAggregator(entries: AggregatorEntry[]): string {
  const parts = [GUARD];
  for (const e of entries) {
    parts.push(`-- ${e.tag}\ndofileifexist([[${toPosix(e.absPath)}]])`);
  }
  return `${parts.join("\n\n")}\n`;
}
